# Import libraries

In [1]:
import sys
github_repo_url = "https://github.com/AnnaEls/HAADF-STEM-image-denoising.git"
!git clone {github_repo_url}
sys.path.append('/content/HAADF-STEM-image-denoising')

Cloning into 'HAADF-STEM-image-denoising'...
remote: Enumerating objects: 995, done.
remote: Counting objects: 100% (591/591), done.
remote: Compressing objects: 100% (582/582), done.
remote: Total 995 (delta 299), reused 0 (delta 0), pack-reused 404 (from 2)
Receiving objects: 100% (995/995), 63.07 MiB | 10.72 MiB/s, done.
Resolving deltas: 100% (401/401), done.

In [2]:
!pip install hyperspy
!pip install atomap

Collecting hyperspy
  Downloading hyperspy-2.5.0-py3-none-any.whl.metadata (7.7 kB)
Requirement already satisfied: cloudpickle in /usr/local/lib/python3.13/dist-packages (from hyperspy) (3.1.2)
Requirement already satisfied: dask>=2024.12.0 in /usr/local/lib/python3.13/dist-packages (from dask[array]>=2024.12.0->hyperspy) (2026.8.0)
Requirement already satisfied: importlib-metadata>=3.6 in /usr/local/lib/python3.13/dist-packages (from hyperspy) (9.0.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.13/dist-packages (from hyperspy) (3.1.6)
Requirement already satisfied: matplotlib>=3.6 in /usr/local/lib/python3.13/dist-packages (from hyperspy) (3.10.0)
Requirement already satisfied: natsort in /usr/local/lib/python3.13/dist-packages (from hyperspy) (8.4.0)
Requirement already satisfied: numpy>=1.25.0 in /usr/local/lib/python3.13/dist-packages (from hyperspy) (2.1.3)
Requirement already satisfied: packaging in /usr/local/lib/python3.13/dist-packages (from hyperspy) (26.3)
Collecting pint>=0.10 (from hyperspy)
  Downloading pint-0.26.1-py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: prettytable>=2.3 in /usr/local/lib/python3.13/dist-packages (from hyperspy) (3.18.0)
Requirement already satisfied: pyyaml in /usr/local/lib/python3.13/dist-packages (from hyperspy) (6.0.3)
Collecting rosettasciio>=0.12.0 (from rosettasciio[hdf5,image]>=0.12.0->hyperspy)
  Downloading rosettasciio-0.15.0-cp313-cp313-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (7.3 kB)
Requirement already satisfied: scipy>=1.10.0 in /usr/local/lib/python3.13/dist-packages (from hyperspy) (1.16.3)
Requirement already satisfied: sympy>=1.10 in /usr/local/lib/python3.13/dist-packages (from hyperspy) (1.14.0)
Requirement already satisfied: tqdm>=4.59.0 in /usr/local/lib/python3.13/dist-packages (from hyperspy) (4.67.3)
Collecting traits>=7.0.0 (from hyperspy)
  Downloading traits-7.2.0-cp313-cp313-manylinux1_x86_64.manylinux_2_28_x86_64.manylinux_2_5_x86_64.whl.metadata (4.8 kB)
Requirement already satisfied: click>=8.1 in /usr/local/lib/python3.13/dist-packages (from dask>=2024.12.0->dask[array]>=2024.12.0->hyperspy) (8.5.0)
Requirement already satisfied: fsspec>=2021.09.0 in /usr/local/lib/python3.13/dist-packages (from dask>=2024.12.0->dask[array]>=2024.12.0->hyperspy) (2025.12.0)
Requirement already satisfied: partd>=1.4.0 in /usr/local/lib/python3.13/dist-packages (from dask>=2024.12.0->dask[array]>=2024.12.0->hyperspy) (1.4.2)
Requirement already satisfied: toolz>=0.12.0 in /usr/local/lib/python3.13/dist-packages (from dask>=2024.12.0->dask[array]>=2024.12.0->hyperspy) (0.12.1)
Requirement already satisfied: zipp>=3.20 in /usr/local/lib/python3.13/dist-packages (from importlib-metadata>=3.6->hyperspy) (4.1.0)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.13/dist-packages (from matplotlib>=3.6->hyperspy) (1.4.0)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.13/dist-packages (from matplotlib>=3.6->hyperspy) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.13/dist-packages (from matplotlib>=3.6->hyperspy) (4.66.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.13/dist-packages (from matplotlib>=3.6->hyperspy) (1.5.1)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.13/dist-packages (from matplotlib>=3.6->hyperspy) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.13/dist-packages (from matplotlib>=3.6->hyperspy) (3.3.3)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.13/dist-packages (from matplotlib>=3.6->hyperspy) (2.9.0.post0)
Collecting flexcache>=0.3 (from pint>=0.10->hyperspy)
  Downloading flexcache-0.3-py3-none-any.whl.metadata (7.0 kB)
Collecting flexparser>=0.4 (from pint>=0.10->hyperspy)
  Downloading flexparser-0.4-py3-none-any.whl.metadata (18 kB)
Requirement already satisfied: platformdirs>=2.1.0 in /usr/local/lib/python3.13/dist-packages (from pint>=0.10->hyperspy) (4.12.2)
Requirement already satisfied: typing-extensions>=4.0.0 in /usr/local/lib/python3.13/dist-packages (from pint>=0.10->hyperspy) (4.16.0)
Requirement already satisfied: wcwidth>=0.3.5 in /usr/local/lib/python3.13/dist-packages (from prettytable>=2.3->hyperspy) (0.9.1)
Requirement already satisfied: python-box!=7.3.1,<8,>=6 in /usr/local/lib/python3.13/dist-packages (from rosettasciio>=0.12.0->rosettasciio[hdf5,image]>=0.12.0->hyperspy) (7.4.1)
Requirement already satisfied: h5py>=3.8.0 in /usr/local/lib/python3.13/dist-packages (from rosettasciio[hdf5,image]>=0.12.0->hyperspy) (3.14.0)
Requirement already satisfied: imageio>=2.27 in /usr/local/lib/python3.13/dist-packages (from rosettasciio[hdf5,image]>=0.12.0->hyperspy) (2.38.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.13/dist-packages (from sympy>=1.10->hyperspy) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.13/dist-packages (from jinja2->hyperspy) (3.0.3)
Requirement already satisfied: locket in /usr/local/lib/python3.13/dist-packages (from partd>=1.4.0->dask>=2024.12.0->dask[array]>=2024.12.0->hyperspy) (1.0.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.13/dist-packages (from python-dateutil>=2.7->matplotlib>=3.6->hyperspy) (1.17.0)
Downloading hyperspy-2.5.0-py3-none-any.whl (1.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.1/1.1 MB 18.3 MB/s eta 0:00:00
Downloading pint-0.26.1-py3-none-any.whl (326 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 326.5/326.5 kB 20.3 MB/s eta 0:00:00
Downloading rosettasciio-0.15.0-cp313-cp313-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (1.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.4/1.4 MB 38.9 MB/s eta 0:00:00
Downloading traits-7.2.0-cp313-cp313-manylinux1_x86_64.manylinux_2_28_x86_64.manylinux_2_5_x86_64.whl (5.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.1/5.1 MB 62.0 MB/s eta 0:00:00
Downloading flexcache-0.3-py3-none-any.whl (13 kB)
Downloading flexparser-0.4-py3-none-any.whl (27 kB)
Installing collected packages: traits, flexparser, flexcache, pint, rosettasciio, hyperspy
Successfully installed flexcache-0.3 flexparser-0.4 hyperspy-2.5.0 pint-0.26.1 rosettasciio-0.15.0 traits-7.2.0
Collecting atomap
  Downloading atomap-0.4.2-py3-none-any.whl.metadata (42 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 42.5/42.5 kB 1.5 MB/s eta 0:00:00
Requirement already satisfied: scipy>=1.4.0 in /usr/local/lib/python3.13/dist-packages (from atomap) (1.16.3)
Requirement already satisfied: numpy>=1.13 in /usr/local/lib/python3.13/dist-packages (from atomap) (2.1.3)
Requirement already satisfied: h5py in /usr/local/lib/python3.13/dist-packages (from atomap) (3.14.0)
Requirement already satisfied: matplotlib>=3.1.0 in /usr/local/lib/python3.13/dist-packages (from atomap) (3.10.0)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.13/dist-packages (from atomap) (1.6.1)
Requirement already satisfied: scikit-image>=0.17.1 in /usr/local/lib/python3.13/dist-packages (from atomap) (0.25.2)
Requirement already satisfied: hyperspy>=2.0.0 in /usr/local/lib/python3.13/dist-packages (from atomap) (2.5.0)
Collecting ase>=3.17.0 (from atomap)
  Downloading ase-3.29.0-py3-none-any.whl.metadata (4.4 kB)
Requirement already satisfied: numba in /usr/local/lib/python3.13/dist-packages (from atomap) (0.61.2)
Collecting exspy (from atomap)
  Downloading exspy-0.3.2-py3-none-any.whl.metadata (45 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 45.2/45.2 kB 2.8 MB/s eta 0:00:00
Requirement already satisfied: typing_extensions>=4.13.1 in /usr/local/lib/python3.13/dist-packages (from ase>=3.17.0->atomap) (4.16.0)
Requirement already satisfied: cloudpickle in /usr/local/lib/python3.13/dist-packages (from hyperspy>=2.0.0->atomap) (3.1.2)
Requirement already satisfied: dask>=2024.12.0 in /usr/local/lib/python3.13/dist-packages (from dask[array]>=2024.12.0->hyperspy>=2.0.0->atomap) (2026.8.0)
Requirement already satisfied: importlib-metadata>=3.6 in /usr/local/lib/python3.13/dist-packages (from hyperspy>=2.0.0->atomap) (9.0.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.13/dist-packages (from hyperspy>=2.0.0->atomap) (3.1.6)
Requirement already satisfied: natsort in /usr/local/lib/python3.13/dist-packages (from hyperspy>=2.0.0->atomap) (8.4.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.13/dist-packages (from hyperspy>=2.0.0->atomap) (26.3)
Requirement already satisfied: pint>=0.10 in /usr/local/lib/python3.13/dist-packages (from hyperspy>=2.0.0->atomap) (0.26.1)
Requirement already satisfied: prettytable>=2.3 in /usr/local/lib/python3.13/dist-packages (from hyperspy>=2.0.0->atomap) (3.18.0)
Requirement already satisfied: pyyaml in /usr/local/lib/python3.13/dist-packages (from hyperspy>=2.0.0->atomap) (6.0.3)
Requirement already satisfied: rosettasciio>=0.12.0 in /usr/local/lib/python3.13/dist-packages (from rosettasciio[hdf5,image]>=0.12.0->hyperspy>=2.0.0->atomap) (0.15.0)
Requirement already satisfied: sympy>=1.10 in /usr/local/lib/python3.13/dist-packages (from hyperspy>=2.0.0->atomap) (1.14.0)
Requirement already satisfied: tqdm>=4.59.0 in /usr/local/lib/python3.13/dist-packages (from hyperspy>=2.0.0->atomap) (4.67.3)
Requirement already satisfied: traits>=7.0.0 in /usr/local/lib/python3.13/dist-packages (from hyperspy>=2.0.0->atomap) (7.2.0)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.13/dist-packages (from matplotlib>=3.1.0->atomap) (1.4.0)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.13/dist-packages (from matplotlib>=3.1.0->atomap) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.13/dist-packages (from matplotlib>=3.1.0->atomap) (4.66.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.13/dist-packages (from matplotlib>=3.1.0->atomap) (1.5.1)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.13/dist-packages (from matplotlib>=3.1.0->atomap) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.13/dist-packages (from matplotlib>=3.1.0->atomap) (3.3.3)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.13/dist-packages (from matplotlib>=3.1.0->atomap) (2.9.0.post0)
Requirement already satisfied: networkx>=3.0 in /usr/local/lib/python3.13/dist-packages (from scikit-image>=0.17.1->atomap) (3.7)
Requirement already satisfied: imageio!=2.35.0,>=2.33 in /usr/local/lib/python3.13/dist-packages (from scikit-image>=0.17.1->atomap) (2.38.0)
Requirement already satisfied: tifffile>=2022.8.12 in /usr/local/lib/python3.13/dist-packages (from scikit-image>=0.17.1->atomap) (2026.9.20)
Requirement already satisfied: lazy-loader>=0.4 in /usr/local/lib/python3.13/dist-packages (from scikit-image>=0.17.1->atomap) (0.6)
Requirement already satisfied: pooch in /usr/local/lib/python3.13/dist-packages (from exspy->atomap) (1.9.0)
Requirement already satisfied: requests in /usr/local/lib/python3.13/dist-packages (from exspy->atomap) (2.32.4)
Requirement already satisfied: llvmlite<0.45,>=0.44.0dev0 in /usr/local/lib/python3.13/dist-packages (from numba->atomap) (0.44.0)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.13/dist-packages (from scikit-learn->atomap) (1.6.0)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.13/dist-packages (from scikit-learn->atomap) (3.7.0)
Requirement already satisfied: click>=8.1 in /usr/local/lib/python3.13/dist-packages (from dask>=2024.12.0->dask[array]>=2024.12.0->hyperspy>=2.0.0->atomap) (8.5.0)
Requirement already satisfied: fsspec>=2021.09.0 in /usr/local/lib/python3.13/dist-packages (from dask>=2024.12.0->dask[array]>=2024.12.0->hyperspy>=2.0.0->atomap) (2025.12.0)
Requirement already satisfied: partd>=1.4.0 in /usr/local/lib/python3.13/dist-packages (from dask>=2024.12.0->dask[array]>=2024.12.0->hyperspy>=2.0.0->atomap) (1.4.2)
Requirement already satisfied: toolz>=0.12.0 in /usr/local/lib/python3.13/dist-packages (from dask>=2024.12.0->dask[array]>=2024.12.0->hyperspy>=2.0.0->atomap) (0.12.1)
Requirement already satisfied: zipp>=3.20 in /usr/local/lib/python3.13/dist-packages (from importlib-metadata>=3.6->hyperspy>=2.0.0->atomap) (4.1.0)
Requirement already satisfied: flexcache>=0.3 in /usr/local/lib/python3.13/dist-packages (from pint>=0.10->hyperspy>=2.0.0->atomap) (0.3)
Requirement already satisfied: flexparser>=0.4 in /usr/local/lib/python3.13/dist-packages (from pint>=0.10->hyperspy>=2.0.0->atomap) (0.4)
Requirement already satisfied: platformdirs>=2.1.0 in /usr/local/lib/python3.13/dist-packages (from pint>=0.10->hyperspy>=2.0.0->atomap) (4.12.2)
Requirement already satisfied: wcwidth>=0.3.5 in /usr/local/lib/python3.13/dist-packages (from prettytable>=2.3->hyperspy>=2.0.0->atomap) (0.9.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.13/dist-packages (from python-dateutil>=2.7->matplotlib>=3.1.0->atomap) (1.17.0)
Requirement already satisfied: python-box!=7.3.1,<8,>=6 in /usr/local/lib/python3.13/dist-packages (from rosettasciio>=0.12.0->rosettasciio[hdf5,image]>=0.12.0->hyperspy>=2.0.0->atomap) (7.4.1)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.13/dist-packages (from sympy>=1.10->hyperspy>=2.0.0->atomap) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.13/dist-packages (from jinja2->hyperspy>=2.0.0->atomap) (3.0.3)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.13/dist-packages (from requests->exspy->atomap) (3.4.9)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.13/dist-packages (from requests->exspy->atomap) (3.20)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.13/dist-packages (from requests->exspy->atomap) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.13/dist-packages (from requests->exspy->atomap) (2026.7.22)
Requirement already satisfied: locket in /usr/local/lib/python3.13/dist-packages (from partd>=1.4.0->dask>=2024.12.0->dask[array]>=2024.12.0->hyperspy>=2.0.0->atomap) (1.0.0)
Downloading atomap-0.4.2-py3-none-any.whl (868 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 868.9/868.9 kB 17.2 MB/s eta 0:00:00
Downloading ase-3.29.0-py3-none-any.whl (3.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.0/3.0 MB 60.8 MB/s eta 0:00:00
Downloading exspy-0.3.2-py3-none-any.whl (603 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 603.8/603.8 kB 29.6 MB/s eta 0:00:00
Installing collected packages: ase, exspy, atomap
Successfully installed ase-3.29.0 atomap-0.4.2 exspy-0.3.2

In [3]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import h5py
import tifffile
from Utilities.Utils import convert
import hyperspy.api as hs
import atomap as am
from Analysis.gaussian_detection_atomap import find_atoms, compare_sublattices_with_lattice_fp_classification, plot_atom_classification

/usr/local/lib/python3.13/dist-packages/hyperspy/misc/_utils.py:1590: VisibleDeprecationWarning: Importing `LazyComplexSignal1D` from `hyperspy._signals.complex_signal1d` is deprecated and will be removed in the HyperSpy 3.0 release. Import it from `hyperspy.signals` instead.
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/hyperspy/misc/_utils.py:1590: VisibleDeprecationWarning: Importing `LazySignal1D` from `hyperspy._signals.signal1d` is deprecated and will be removed in the HyperSpy 3.0 release. Import it from `hyperspy.signals` instead.
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/hyperspy/misc/_utils.py:1590: VisibleDeprecationWarning: Importing `LazySignal1D` from `hyperspy._signals.signal1d` is deprecated and will be removed in the HyperSpy 3.0 release. Import it from `hyperspy.signals` instead.
  warnings.warn(

# Setting parameters

In [4]:
dataset_path = '/content/HAADF-STEM-image-denoising/Datasets/'
data_file = dataset_path + 'wei_atom_subset_WS2_contrast_variation.h5'

metadata_subset = pd.read_hdf(data_file, key="metadata")

with h5py.File(data_file, "r") as f:
    print("Top-level keys:", list(f.keys()))
    print("Images:", list(f["imgs"].keys()))
    print("Raw:", list(f["raw"].keys()))
    print("Coordinates:", list(f["coords"].keys()))

print("\nMetadata:")
display(metadata_subset)

Top-level keys: ['coords', 'imgs', 'metadata', 'raw']
Images: ['0123', '0124', '0125', '0126', '0127', '0128', '0129', '0130']
Raw: ['0123', '0124', '0125', '0126', '0127', '0128', '0129', '0130']
Coordinates: ['0123', '0124', '0125', '0126', '0127', '0128', '0129', '0130']

Metadata:

,key,Atoms/px,Material_orientation,Spacegroup,Type,contrast,dose_e-/Å²,peakintensity_e-,pixelsize_pm,probe_current_pA,resolution_pm,flybackerror,poisson_dB,randomdrift
123,0123,8.393051,WS2[0001],P63/mmc[194],experimental,0.159,116783.034798,2502.422276,15.46,22.33,98.0,NaN,NaN,NaN
124,0124,8.393051,WS2[0001],P63/mmc[194],experimental,0.133,116783.034798,2365.907658,15.46,22.33,98.0,NaN,NaN,NaN
125,0125,8.393051,WS2[0001],P63/mmc[194],experimental,0.101,116783.034798,2229.216597,15.46,22.33,98.0,NaN,NaN,NaN
126,0126,8.393051,WS2[0001],P63/mmc[194],experimental,0.060,116783.034798,3164.079849,15.46,22.33,98.0,NaN,NaN,NaN
127,0127,8.393051,WS2[0001],P63/mmc[194],experimental,0.048,116783.034798,4146.385107,15.46,22.33,98.0,NaN,NaN,NaN
128,0128,8.393051,WS2[0001],P63/mmc[194],experimental,0.037,116783.034798,4616.112008,15.46,22.33,98.0,NaN,NaN,NaN
129,0129,8.393051,WS2[0001],P63/mmc[194],experimental,0.109,116783.034798,2270.713104,15.46,22.33,98.0,NaN,NaN,NaN
130,0130,8.393051,WS2[0001],P63/mmc[194],experimental,0.087,116783.034798,2179.196693,15.46,22.33,98.0,NaN,NaN,NaN

In [5]:
key = "0128"

with h5py.File(data_file, "r") as f:
    img = f["imgs"][key][:]
    raw = f["raw"][key][:]
    coords = f["coords"][key][:]

print("Image shape:", img.shape)
print("Raw shape:", raw.shape)
print("Coordinates shape:", coords.shape)

Image shape: (256, 256)
Raw shape: (256, 256)
Coordinates shape: (297, 2)

In [6]:
SEPARATION = 4
MATCH_TOLERANCE = 5.0
LATTICE_TOLERANCE = 5.0
NEIGHBOR_RADIUS = 25

# Analysis

In [ ]:
keys = ["0123", "0124", "0129", "0125", "0130", "0126", "0127", "0128"]
rows = []
for key in keys:
    print("Image ID:" , key)
    output_path = f"/content/HAADF-STEM-image-denoising/Datasets/DATASET_WEI_ATOM_WS2_CONTRAST/denoised_unit/"
    image_path = output_path + "Image_ID_" + key + "_unit_aligned.tif"
    image = tifffile.imread(image_path)
    plt.imshow(image, cmap = "gray"); plt.axis("off"); plt.title("Image")
    plt.show()

In [ ]:
keys = ["0123", "0124", "0125", "0126", "0127", "0128", "0129", "0130"]
rows = []
for key in keys:
    print("Image ID:" , key)
    output_path = f"/content/HAADF-STEM-image-denoising/Datasets/DATASET_WEI_ATOM_WS2_CONTRAST/denoised_unit/"
    image_path = output_path + "Image_ID_" + key + "_unit_aligned.tif"
    image = convert(tifffile.imread(image_path))
    s = hs.load(image_path)
    noisy_sublattice = find_atoms(s, separation = SEPARATION, plot = True)
    plt.show()
    atom_data = []
    for atom in noisy_sublattice.atom_list:
      atom_data.append({
        'x': atom.pixel_x,
        'y': atom.pixel_y,
        'sx': atom.sigma_x,
        'sy': atom.sigma_y,
        'r': atom.rotation,
        'e': atom.ellipticity,
        'amplitude_gaussian': atom.amplitude_gaussian
       })

    with h5py.File(data_file, "r") as f:
        coordinates = f["coords"][key][:]

    reference_sublattice = am.sublattice.Sublattice(
        atom_position_list=coordinates,
        image=image
     )
    results = compare_sublattices_with_lattice_fp_classification(
        reference_sublattice,
        noisy_sublattice,
        image_shape=image.shape,
        match_tolerance=MATCH_TOLERANCE,
        lattice_tolerance=LATTICE_TOLERANCE,
        neighbor_radius=NEIGHBOR_RADIUS)
    plot_atom_classification(image, reference_sublattice, noisy_sublattice, results)
    contrast = metadata_subset.loc[metadata_subset["key"] == key, "contrast"].values[0]
    rows.append({"contrast": contrast, "rmse": np.round(results["rmse_error"], 2), "TP": results["num_true_positives"], "FN": results["num_false_negatives"], "FP": results["num_false_positives"] })

In [10]:
N_TP = len(reference_sublattice.atom_list)
df_results = pd.DataFrame(rows)
df_results = df_results.sort_values(by="contrast",ascending=False)
df_results['status'] = df_results.apply(
    lambda row: 'failed' if (row['FP'] > (0.5 * N_TP)) or (row['TP'] < (0.5 * N_TP)) else 'passed',
    axis=1
)
display(df_results)

   contrast  rmse   TP  FN   FP  status
0     0.159  0.62  297   0   49  passed
1     0.133  0.77  297   0   37  passed
6     0.109  0.90  294   3   49  passed
2     0.101  1.10  295   2   61  passed
7     0.087  1.39  296   1   78  passed
3     0.060  1.63  292   5  110  passed
4     0.048  2.21  277  20  146  passed
5     0.037  2.32  271  26  167  failed